#!/usr/bin/env bash
# validate-audit.sh -- proves the audit botlish-native (built by
# audit/post-m8a-common-inefficiency/tools/build-audit-native.sh from
# audit-native.patch) is representative of the production binary for one
# NIR program (POST-R2A-DYNAMIC-CENSUS.md, "Audit build validation").
# Observation only.
#
#   bash audit/post-r2a-dynamic-census/tools/validate-audit.sh PROD-BIN AUDIT-BIN PROGRAM.nir
#
# Checks, each printed as OK/DIFF:
#   value       `run` output (program value) identical
#   size        `size` (total + per-function machine bytes) identical
#   object      `object` relocatable object file byte-identical (the same
#               Cranelift pipeline JIT uses, minus final relocation)
#   vcode       `vcode` (post-lowering, pre-regalloc VCode) identical
#   alloc       `run --alloc summary` identical (allocation counters)
#   sites       `run --alloc sites` identical (allocation site table)
#   jitmap      the audit build's BOTLISH_AUDIT_JITMAP direct + generic-entry
#               sizes equal `size`'s per-function sizes, in order (so every
#               generated byte `size` counts is covered by a named range)
set -u
prod=${1:?usage}; audit=${2:?usage}; nir=${3:?usage}
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
export LANG=C.utf8 LC_ALL=C.utf8
status=0
check() {
    if cmp -s "$tmp/p.$1" "$tmp/a.$1"; then echo "OK    $1"; else echo "DIFF  $1"; status=1; fi
}
"$prod"  run "$nir" > "$tmp/p.value" 2>&1
"$audit" run "$nir" > "$tmp/a.value" 2>&1
check value
"$prod"  size "$nir" > "$tmp/p.size"
"$audit" size "$nir" > "$tmp/a.size"
check size
"$prod"  object "$tmp/p.o" "$nir" > /dev/null
"$audit" object "$tmp/a.o" "$nir" > /dev/null
cp "$tmp/p.o" "$tmp/p.object"; cp "$tmp/a.o" "$tmp/a.object"
check object
"$prod"  vcode "$nir" > "$tmp/p.vcode"
"$audit" vcode "$nir" > "$tmp/a.vcode"
check vcode
"$prod"  run "$nir" --alloc summary > "$tmp/p.alloc"
"$audit" run "$nir" --alloc summary > "$tmp/a.alloc"
check alloc
"$prod"  run "$nir" --alloc sites > "$tmp/p.sites"
"$audit" run "$nir" --alloc sites > "$tmp/a.sites"
check sites
BOTLISH_AUDIT_JITMAP="$tmp/jitmap" "$audit" bench 1 "$nir" > /dev/null
awk '{print $4 + $6}' "$tmp/jitmap" | tr '\n' ' ' | sed 's/ $//' > "$tmp/a.jitmap"
tclsh9.0 <<EOF > "$tmp/p.jitmap"
set f [open $tmp/p.size]; set l [read \$f]; close \$f
puts -nonewline [join [lindex \$l 2] { }]
EOF
check jitmap
echo "value: $(grep '^value' "$tmp/p.value" | cut -c1-80)"
echo "size:  $(cut -c1-40 "$tmp/p.size")"
exit $status
