[package]
name = "botlish-native"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
cranelift-codegen = { version = "0.135", features = ["trace-log"] }
cranelift-frontend = "0.135"
cranelift-module = "0.135"
cranelift-jit = "0.135"
cranelift-object = "0.135"
cranelift-native = "0.135"
libc = "0.2"
log = "0.4"
num-bigint = "0.4"
num-traits = "0.2"
unicode-general-category = "1.1.0"

[profile.release]
debug = 1
