# hashtable.tcl -- benchmarks and metrics for examples/stdlib/hashtable.bot
# (the hash-table milestone's adversarial workload), on the native backend.
#
#   tclsh bench/hashtable.tcl [-sizes N N N] [-runs N]
#
# Reports, per size, in the shape milestone req #60 asks for:
#
#   construction: allocations, bytes, MutableArray allocations (so resizes
#                 = (mutarrayAllocs - 4) / 3), presized vs default, time
#   operations:   hit / miss / replace / delete -- allocations beyond a
#                 table-already-built baseline (must be 0: req #19), time
#
# Probe/hash-call/comparison counts are NOT instrumented into
# hashtable.bot itself (req #50, #57: keep the core implementation boring,
# a plain workload for the compiler/runtime, not distorted by counters).
# Instead this script runs a plain Tcl model of the *identical* algorithm
# (same hash/mod primitives, same linear probing) purely to count probes,
# as req #21 explicitly allows ("these counters may live in benchmark
# instrumentation... a diagnostic table variant").

set root [file dirname [file dirname [file normalize [info script]]]]
source [file join $root core core.tcl]
source [file join $root compiler compiler.tcl]
source [file join $root surface surface.tcl]
source [file join $root native native.tcl]

interp recursionlimit {} 2000000

# ---------------------------------------------------------------------------
# The implementation under test, as a source prefix (definitions only, no
# trailing sample() call -- see tests/native-hashtable.test's header for why).

set hashtableSource [regsub {\nsample\(\)\n$} \
    [core::ReadFile [file join $root examples stdlib hashtable.bot]] "\n"]

proc hirOf {text} {
    global hashtableSource
    return [surface::compile "$hashtableSource\n$text\n" bench.bot -strict 0]
}

proc measureBest {text runs} {
    lassign [native::measure [hirOf $text] $runs] lower compile best collections value
    return [list $best $value]
}

proc allocationsOf {text} {
    return [native::allocationReport [hirOf $text] summary]
}

# ---------------------------------------------------------------------------
# Program text generators. Keys are "key<i>" (String) or i (Int).

proc keyExpr {kind i} {
    if {$kind eq "str"} {
        return "\"key$i\""
    }
    return $i
}

# Botlish has no Int-to-String conversion (a real gap noted in the final
# report), so a String key naming index I cannot be produced by a Botlish
# loop computing "key" ++ str(I) at run time -- there is no str(I). Every
# String-keyed program below is therefore generated by *unrolling*: this
# Tcl script emits N distinct literal ht_set(t, "keyI", I) lines directly,
# rather than a Botlish-level loop. Int keys need no such workaround (the
# loop counter is already a usable key), so they use ordinary Botlish tail
# recursion and scale to much larger N here.

proc buildProgram {n kind {presize 0}} {
    set ctor [expr {$presize ? "ht_new_sized($n)" : "ht_new()"}]
    if {$kind eq "str"} {
        set lines {}
        for {set i 0} {$i < $n} {incr i} {
            lappend lines "    ht_set(t, \"key$i\", $i)"
        }
        return "fn f():\n    t = $ctor\n[join $lines \n]\n    ht_size(t)\nf()\n"
    }
    return "
fn build(t, i, n):
    if i >= n:
        return t
    ht_set(t, i, i)
    build(t, i + 1, n)

fn f():
    t = build($ctor, 0, $n)
    ht_size(t)
f()
"
}

# Builds N entries, then performs M lookups of existing keys (HIT), of keys
# guaranteed absent (MISS, offset past N), or M replacements (REPLACE).
proc opProgram {n kind op m} {
    if {$kind eq "str"} {
        set lines {}
        for {set i 0} {$i < $n} {incr i} {
            lappend lines "    ht_set(t, \"key$i\", $i)"
        }
        set ops {}
        for {set i 0} {$i < $m} {incr i} {
            set j [expr {$i % $n}]
            switch -- $op {
                hit     { lappend ops "    ht_get(t, \"key$j\")" }
                miss    { lappend ops "    ht_get(t, \"key[expr {$i + $n}]\")" }
                replace { lappend ops "    ht_set(t, \"key$j\", [expr {$i + $n}])" }
            }
        }
        return "fn f():\n    t = ht_new_sized($n)\n[join $lines \n]\n[join $ops \n]\n    ht_size(t)\nf()\n"
    }
    switch -- $op {
        hit     { set loopBody "ht_get(t, j)" }
        miss    { set loopBody "ht_get(t, i + n)" }
        replace { set loopBody "ht_set(t, j, i + n)" }
    }
    return "
fn build(t, i, n):
    if i >= n:
        return t
    ht_set(t, i, i)
    build(t, i + 1, n)

fn doOps(t, i, m, n):
    if i >= m:
        return unit
    j = mod(i, n)
    $loopBody
    doOps(t, i + 1, m, n)

fn f():
    t = build(ht_new_sized($n), 0, $n)
    doOps(t, 0, $m, $n)
    ht_size(t)
f()
"
}

proc deleteAllProgram {n kind} {
    if {$kind eq "str"} {
        set lines {}
        for {set i 0} {$i < $n} {incr i} {
            lappend lines "    ht_set(t, \"key$i\", $i)"
        }
        set dels {}
        for {set i 0} {$i < $n} {incr i} {
            lappend dels "    ht_delete(t, \"key$i\")"
        }
        return "fn f():\n    t = ht_new_sized($n)\n[join $lines \n]\n[join $dels \n]\n    ht_size(t)\nf()\n"
    }
    return "
fn build(t, i, n):
    if i >= n:
        return t
    ht_set(t, i, i)
    build(t, i + 1, n)

fn deleteAll(t, i, n):
    if i >= n:
        return unit
    ht_delete(t, i)
    deleteAll(t, i + 1, n)

fn f():
    t = build(ht_new(), 0, $n)
    deleteAll(t, 0, $n)
    ht_size(t)
f()
"
}

# ---------------------------------------------------------------------------
# Tcl-side model of the identical algorithm, purely for probe/hash-call/
# comparison counts (see the file header).

proc modelHash {v} {
    set c [core::native::invoke [core::value::native hash] [list $v]]
    return [core::value::intOf [lindex $c 1]]
}

# Simulates inserting N sequential keys (String or Int) into a table that
# starts at capacity 8 and doubles under the same 2/3 load-factor policy;
# returns a dict of counters: hashCalls, probeSteps (control-slot visits),
# comparisons (key == comparisons at OCCUPIED slots), resizes, entriesRehashed.
proc modelBuild {n kind} {
    set capacity 8
    set controls [lrepeat $capacity 0]
    set keys [lrepeat $capacity ""]
    set size 0
    set tombstones 0
    set counters [dict create hashCalls 0 probeSteps 0 comparisons 0 resizes 0 entriesRehashed 0]
    for {set i 0} {$i < $n} {incr i} {
        set key [expr {$kind eq "str" ? "key$i" : $i}]
        dict incr counters hashCalls
        set start [expr {[modelHash [core::value::str $key]] % $capacity}]
        set index $start
        set firstTombstone -1
        while 1 {
            dict incr counters probeSteps
            set state [lindex $controls $index]
            if {$state == 0} {
                break
            }
            if {$state == 1} {
                dict incr counters comparisons
            }
            set index [expr {($index + 1) % $capacity}]
        }
        set target [expr {$firstTombstone >= 0 ? $firstTombstone : $index}]
        set occupied [expr {$size + $tombstones}]
        if {($occupied + 1) * 3 > $capacity * 2} {
            # Grow: rehash every occupied key into a fresh table (no
            # tombstones exist in this pure-insert model).
            set newCapacity [expr {$capacity * 2}]
            set newControls [lrepeat $newCapacity 0]
            set newKeys [lrepeat $newCapacity ""]
            for {set j 0} {$j < $capacity} {incr j} {
                if {[lindex $controls $j] != 1} {
                    continue
                }
                set k [lindex $keys $j]
                dict incr counters hashCalls
                dict incr counters entriesRehashed
                set idx [expr {[modelHash [core::value::str $k]] % $newCapacity}]
                while {[lindex $newControls $idx] != 0} {
                    set idx [expr {($idx + 1) % $newCapacity}]
                }
                lset newControls $idx 1
                lset newKeys $idx $k
            }
            dict incr counters resizes
            set capacity $newCapacity
            set controls $newControls
            set keys $newKeys
            set target [expr {[modelHash [core::value::str $key]] % $capacity}]
            while {[lindex $controls $target] != 0} {
                set target [expr {($target + 1) % $capacity}]
            }
        }
        lset controls $target 1
        lset keys $target $key
        incr size
    }
    dict set counters finalCapacity $capacity
    return $counters
}

# ---------------------------------------------------------------------------
# Report

proc mutarrayResizes {report} {
    set allocs [dict get $report byKind MutableArray allocations]
    return [expr {($allocs - 4) / 3}]
}

proc row {args} {
    puts [format "  %-10s %-8s %-10s %10s %14s %10s %10s" {*}$args]
}

# A flat list N1 int N2 int ... N1 str N2 str ... suitable for
# "foreach {n kind} [sizeKindPairs ...]" -- concat of two lmaps of 2-tuples
# does NOT flatten (each tuple stays a nested list element), so this builds
# the flat sequence directly instead.
proc sizeKindPairs {sizes strSizes} {
    set pairs {}
    foreach n $sizes { lappend pairs $n int }
    foreach n $strSizes { lappend pairs $n str }
    return $pairs
}

# Sizes per kind: Int keys need no source unrolling (req #29's own
# suggestion -- Int keys isolate hashing/probing cost from String cost --
# doubles here as the one that scales), so they run the full SIZES list.
# String keys are generated by unrolling literal ht_set/ht_get/ht_delete
# lines (see the file header): capped lower so generated source size and
# compile time stay reasonable.
proc report {sizes strSizes runs} {
    puts "Construction (native backend, best of $runs runs, presized vs default)"
    row entries kind presize allocations allocatedBytes resizes time-us
    foreach {n kind} [sizeKindPairs $sizes $strSizes] {
        foreach presize {0 1} {
            set text [buildProgram $n $kind $presize]
            lassign [measureBest $text $runs] best value
            set report [allocationsOf $text]
            row $n $kind $presize [dict get $report total allocations] \
                [dict get $report total allocatedBytes] [mutarrayResizes $report] $best
        }
    }
    puts ""
    puts "Operations (native backend, presized table, best of $runs runs; alloc/op must be 0)"
    row entries kind op {alloc/op} {} time-us/op {}
    foreach {n kind} [sizeKindPairs $sizes $strSizes] {
        set m [expr {min($n, 5000)}]
        foreach op {hit miss replace} {
            set built [buildProgram $n $kind 1]
            set withOps [opProgram $n $kind $op $m]
            set baseAllocs [dict get [allocationsOf $built] total allocations]
            set opAllocs [dict get [allocationsOf $withOps] total allocations]
            lassign [measureBest $withOps $runs] best value
            set perOp [expr {double($best) / $m}]
            row $n $kind $op [expr {$opAllocs - $baseAllocs}] {} [format %.3f $perOp] {}
        }
        set delText [deleteAllProgram $n $kind]
        lassign [measureBest $delText $runs] best value
        row $n $kind delete-all {} {} [format %.3f [expr {double($best) / $n}]] {}
    }
    puts ""
    puts "Probe metrics (Tcl-side model of the identical algorithm: see file header)"
    row entries kind hashCalls probeSteps comparisons resizes entriesRehashed
    foreach {n kind} [sizeKindPairs $sizes $strSizes] {
        set counters [modelBuild $n $kind]
        row $n $kind [dict get $counters hashCalls] [dict get $counters probeSteps] \
            [dict get $counters comparisons] [dict get $counters resizes] [dict get $counters entriesRehashed]
    }
}

set sizes {100 10000 100000}
set strSizes {100 2000}
set runs 3
for {set i 0} {$i < [llength $argv]} {incr i} {
    switch -- [lindex $argv $i] {
        -sizes { set sizes {} ; incr i ; while {$i < [llength $argv] && [string is integer [lindex $argv $i]]} { lappend sizes [lindex $argv $i] ; incr i } ; incr i -1 }
        -str-sizes { set strSizes {} ; incr i ; while {$i < [llength $argv] && [string is integer [lindex $argv $i]]} { lappend strSizes [lindex $argv $i] ; incr i } ; incr i -1 }
        -runs  { set runs [lindex $argv [incr i]] }
    }
}

report $sizes $strSizes $runs
